# This file based on https://gist.github.com/mwouts/9842452d020c08faf9e84a3bba38a66f
# 2020-06-22 - slg - customized
#
name: CI (pip, flake8, pytest)
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -r requirements.txt ]; then pip install -r requirements.txt ; fi
          if [ -r requirements-dev.txt ]; then pip install -r requirements-dev.txt ; fi

          # nltk
          python -c 'import nltk;nltk.download("punkt");'
          python -c 'import nltk;nltk.download("averaged_perceptron_tagger");'

          # Install program analysis tools
          pip install black flake8 autopep8 || true
          pip install autopep8 || true

      - name: Test with pytest
        run: |
          pip install pytest
          pytest --cov=./ --cov-report=xml python

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true
            
