name: Archiver CI

on: [push, pull_request]

jobs:
  archiver:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: archiver
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Check
        run: make check
      - name: Pylint
        run: make pylint
